### ISSUE TITLE
Typo/formatting error in language map for prefLabel of feide-clientinfo

### ISSUE THREAD

**Issue by geirfp** [KS-AVT/avt#25]
Hi @samuelsenj,
At (line 70) https://github.com/KS-AVT/avt/blob/AVT2/avt.jsonld#L70 there is a small typo which causes a formatting error. A semicolon is used where there instead should be a colon in order for the profile to validate as JSON-LD.

**Comment by stdob** [comment]
https://github.com/KS-AVT/avt/pull/26
